$id: "https://dataworks.stanford.edu/dataworks-0.0.1.yml"
title: Dataworks Schema
description: >
  A schema for validating dataset metadata for the Dataworks application.

  Unless otherwise specified, this schema is based on the DataCite Metadata Schema (https://schema.datacite.org/)
type: object
properties:
  creators:
    type: array
    items:
      $ref: '#/components/schemas/Creator'
    minItems: 1
  titles:
    type: array
    items:
      $ref: '#/components/schemas/Title'
    minItems: 1
  publisher:
    $ref: '#/components/schemas/Publisher'
  publication_year:
    type: string
    pattern: '^[1-2][0-9]{3}$'
  subjects:
    type: array
    items:
      $ref: '#/components/schemas/Subject'
  contributors:
    type: array
    items:
      $ref: '#/components/schemas/Contributor'
    minItems: 1
  descriptions:
    type: array
    items:
      $ref: '#/components/schemas/Description'
    minItems: 1
  dates:
    type: array
    items:
      $ref: '#/components/schemas/Date'
    minItems: 1
  language:
    type: string
    pattern: '^[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*$'
  identifiers:
    type: array
    items:
      $ref: '#/components/schemas/Identifier'
    minItems: 1
  related_identifiers:
    type: array
    items:
      $ref: '#/components/schemas/RelatedIdentifier'
    minItems: 1
  sizes:
    type: array
    items:
      type: string
    minItems: 1
  formats:
    type: array
    items:
      type: string
    minItems: 1
  version:
    type: string
  rights_list:
    type: array
    items:
      $ref: '#/components/schemas/Rights'
    minItems: 1
  funding_references:
    type: array
    items:
      $ref: '#/components/schemas/FundingReference'
    minItems: 1
  url:
    description: Landing page for the dataset
    type: string
    format: uri,
  access:
    type: string
    enum:
      - Public
      - Restricted
  variables:
    description: A list of variables in the dataset
    type: array
    items:
      type: string
    minItems: 1
  data_use_statement:
    type: string
  provider:
    description: The provider of the dataset metadata
    type: string
    enum:
      - DataCite
      - Dryad
      - Local
      - Redivis
      - Zenodo
      - SearchWorks
required:
  - titles
  - creators
  - publication_year
  - identifiers
  - url
  - access
  - provider
additionalProperties: false
components:
  schemas:
    Contributor:
      allOf:
        - $ref: '#/components/schemas/PersonOrOrganization'
        - type: object
          properties:
            contributor_type:
              type: string
              enum:
                - ContactPerson
                - DataCollector
                - DataCurator
                - DataManager
                - Distributor
                - Editor
                # Funder is not in controlled list, but is in DataCite data.
                - Funder
                - HostingInstitution
                - Producer
                - ProjectLeader
                - ProjectManager
                - ProjectMember
                - RegistrationAgency
                - RegistrationAuthority
                - RelatedPerson
                - Researcher
                - ResearchGroup
                - RightsHolder
                - Sponsor
                - Supervisor
                - Translator
                - WorkPackageLeader
                - Other
      unevaluatedProperties: false
    Creator:
      allOf:
        - $ref: '#/components/schemas/PersonOrOrganization'
      unevaluatedProperties: false
    Date:
      type: object
      properties:
        date:
          type: string
          anyOf:
            - format: date-time
            - format: date
            - pattern: '^[0-2][0-9]{3}(-[0-1][0-9](-[0-3][0-9](T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{3})?Z)?)?)?/[0-2][0-9]{3}(-[0-1][0-9](-[0-3][0-9](T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{3})?Z)?)?)?$'
            - pattern: '^[0-2][0-9]{3}(-[0-1][0-9])?$'

        date_type:
          type: string
          enum:
            - Accepted
            - Available
            - Copyrighted
            - Collected
            - Coverage
            - Created
            - Issued
            - Submitted
            - Updated
            - Valid
            - Withdrawn
            - Other
      required:
        - date
        # date_type is required in Datacite, but optional here.
      additionalProperties: false
    Description:
      type: object
      properties:
        description:
          type: string
        description_type:
          type: string
          enum:
            - Abstract
            - Methods
            - SeriesInformation
            - TableOfContents
            - TechnicalInfo
            - Other
      required:
        - description
        # description_type is required in Datacite, but optional here.
      additionalProperties: false
    FundingReference:
      type: object
      properties:
        funder_name:
          type: string
        funder_identifier:
          type: string
        funder_identifier_type:
          type: string
          enum:
            - Crossref Funder ID
            - DOI
            - GRID
            - ISNI
            - ROR
            - Other
        award_number:
          type: string
        award_uri:
          type: string
        award_title:
          type: string
      required:
        - funder_name
      dependentRequired:
        funder_identifier:
          - funder_identifier_type
      additionalProperties: false    
    PersonOrOrganization:
      type: object
      properties:
        name:
          type: string
        name_type:
          type: string
          enum:
            - Personal
            - Organizational
        given_name:
          type: string
        family_name:
          type: string
        name_identifiers:
          type: array
          items:
            type: object
            properties:
              name_identifier:
                type: string
              name_identifier_scheme:
                type: string
                enum:
                  # These are the examples schemes from DataCite. Additional schemes may be added.
                  - ORCID
                  - ISNI
                  - ROR
                  - FundRef
                  - Other
              required:
                - name_identifier
                - name_identifier_scheme
          minItems: 1
        # Yes, this is singular in the DataCite schema.
        affiliation:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              affiliation_identifier:
                type: string
              affiliation_identifier_scheme:
                type: string
                enum:
                  # These are the examples schemes from DataCite. Additional schemes may be added.
                  - GRID
                  - ISNI
                  - ROR
            anyOf:
              required:
                - name
              required:
                - affiliation_identifier
            dependentRequired:
              affiliation_identifier:
                - affiliation_identifier_scheme
          minItems: 1
      required:
        - name
        # creator_type is required in Datacite, but optional here.
    Publisher:
      type: object
      properties:
        name:
          type: string
        publisher_identifier:
          type: string
        publisher_identifier_scheme:
          type: string
          enum:
            # These are the examples schemes from DataCite. Additional schemes may be added.
            - ROR
            - re3data
            - VIAF
            - Wikidata
            - Crossref Funder ID
            - ISNI
            - OpenDOAR
            - FAIRsharing
            - ISSN
      anyOf:
        required:
          - name
        required:
          - publisher_identifier
      dependentRequired:
        publisher_identifier:
          - publisher_identifier_scheme
    RelatedIdentifier:
      type: object
      properties:
        related_identifier:
          type: string
        related_identifier_type:
          type: string
          enum:
            - ARK
            - arXiv
            - bibcode
            - CSTR
            - DOI
            - EAN8
            - EAN13
            - EISSN
            - Handle
            - IGSN
            - ISBN
            - ISSN
            - ISTC
            - LISSN
            - LSID
            - PMID
            - PURL
            - RRID
            - UPC
            - URL
            - URN
            - w3id
        relation_type:
          type: string
          enum:
            - IsCitedBy
            - Cites
            - IsSupplementTo
            - IsSupplementedBy
            - IsContinuedBy
            - Continues
            - IsDescribedBy
            - Describes
            - HasMetadata
            - IsMetadataFor
            - HasVersion
            - IsVersionOf
            - IsNewVersionOf
            - IsPreviousVersionOf
            - IsPartOf
            - HasPart
            - IsPublishedIn
            - IsReferencedBy
            - References
            - IsDocumentedBy
            - Documents
            - IsCompiledBy
            - Compiles
            - IsVariantFormOf
            - IsOriginalFormOf
            - IsIdenticalTo
            - IsReviewedBy
            - Reviews
            - IsDerivedFrom
            - IsSourceOf
            - IsRequiredBy
            - Requires
            - IsObsoletedBy
            - Obsoletes
            - IsCollectedBy
            - Collects
            - IsTranslationOf
            - HasTranslation
        resource_type_general:
          type: string
          enum:
            - Audiovisual
            - Award
            - Book
            - BookChapter
            - Collection
            - ComputationalNotebook
            - ConferencePaper
            - ConferenceProceeding
            - DataPaper
            - Dataset
            - Dissertation
            - Event
            - Image
            - InteractiveResource
            - Instrument
            - Journal
            - JournalArticle
            - Model
            - OutputManagementPlan
            - PeerReview
            - PhysicalObject
            - Preprint
            - Project
            - Report
            - Service
            - Software
            - Sound
            - Standard
            - StudyRegistration
            - Text
            - Workflow
            - Other
      required:
        - related_identifier
        # related_identifier_type, relation_type is required in Datacite, but optional here.
      additionalProperties: false
    Rights:
      type: object
      properties:
        rights:
          type: string
        rights_uri:
          type: string
          format: uri
        rights_identifier:
          type: string
        rights_identifier_scheme:
          type: string
      anyOf:
        required:
          - rights
        required:
          - rights_uri
      additionalProperties: false
    Subject:
      type: object
      properties:
        subject:
          type: string
        subject_scheme:
          type: string
        value_uri:
          type: string
          format: uri
      required:
        - subject
      additionalProperties: false
    Title:
      type: object
      properties:
        title:
          type: string
        title_type:
          type: string
          enum:
            - AlternativeTitle
            - Subtitle
            - TranslatedTitle
            - Other
      required:
        - title
      additionalProperties: false
    Identifier:
      type: object
      properties:
        identifier:
          type: string
        identifier_type:
          type: string
          # Recommended values:
          #   - DOI
          #   - RedivisReference
          #   - SearchWorksReference
          #   - ZenodoId
      required:
        - identifier
        - identifier_type
      additionalProperties: false
